# GitHub Copilot Agent Configuration
#
# This file configures permissions and environment for the GitHub Copilot coding agent.
# The Copilot agent needs access to GITHUB_TOKEN to install dependencies from the
# GitHub Package Registry (@keetanetwork scope).

# Grant Copilot agent permission to read packages from GitHub Package Registry
permissions:
  packages: read
  contents: write
  pull-requests: write
  issues: write

# Make GITHUB_TOKEN available to the Copilot agent environment
# This allows Copilot to run `make test` which requires authentication
# to install dependencies from GitHub Package Registry
secrets:
  - GITHUB_TOKEN
