#!/usr/bin/env bash
if [[ "$1" = "off" ]]
then
   if [[ -n $ANCHOR_TESTING_FIRESTORE_DOCKER_ID ]]
   then
      docker stop $ANCHOR_TESTING_FIRESTORE_DOCKER_ID > /dev/null
   fi
   echo "unset ANCHOR_TESTING_FIRESTORE_DOCKER_ID"
   echo "unset ANCHOR_TESTING_FIRESTORE_HOST"
   echo "unset ANCHOR_TESTING_FIRESTORE_PORT"
else
   # Use -p 0:8080 to let Docker automatically assign a random available host port
   id="$(docker run --detach -p 0:8080 --rm google/cloud-sdk:emulators gcloud beta emulators firestore start --host-port=0.0.0.0:8080)"
   ALREADY_WAITED=0
   until docker logs $id 2>&1 | grep -q "Dev App Server is now running"
   do 
      sleep 1;
      ALREADY_WAITED=$(($ALREADY_WAITED+1))
      if [ $ALREADY_WAITED -gt 30 ]
      then
         echo "Waiting for Firestore timed-out" 1>&2
         exit 64
      fi 
   done
   port="$(docker port "${id}" 8080 | cut -d: -f2)"

   echo "export ANCHOR_TESTING_FIRESTORE_DOCKER_ID=${id}"
   echo "export ANCHOR_TESTING_FIRESTORE_HOST=127.0.0.1"
   echo "export ANCHOR_TESTING_FIRESTORE_PORT=${port}"
fi
