import { createAssertEquals } from 'typia';
import type {
	KeetaNotificationAnchorListTargetsRequestJSON,
	KeetaNotificationAnchorDeleteTargetRequestJSON,
	KeetaNotificationAnchorRegisterTargetRequestJSON,
	KeetaNotificationAnchorCreateSubscriptionRequestJSON,
	KeetaNotificationAnchorDeleteSubscriptionRequestJSON,
	KeetaNotificationAnchorListSubscriptionsRequestJSON
} from './common.js';

export const assertKeetaNotificationAnchorListTargetsRequestJSON: ReturnType<typeof createAssertEquals<KeetaNotificationAnchorListTargetsRequestJSON>> = createAssertEquals<KeetaNotificationAnchorListTargetsRequestJSON>();
export const assertKeetaNotificationAnchorRegisterTargetRequestJSON: ReturnType<typeof createAssertEquals<KeetaNotificationAnchorRegisterTargetRequestJSON>> = createAssertEquals<KeetaNotificationAnchorRegisterTargetRequestJSON>();
export const assertKeetaNotificationAnchorDeleteTargetRequestJSON: ReturnType<typeof createAssertEquals<KeetaNotificationAnchorDeleteTargetRequestJSON>> = createAssertEquals<KeetaNotificationAnchorDeleteTargetRequestJSON>();
export const assertKeetaNotificationAnchorCreateSubscriptionRequestJSON: ReturnType<typeof createAssertEquals<KeetaNotificationAnchorCreateSubscriptionRequestJSON>> = createAssertEquals<KeetaNotificationAnchorCreateSubscriptionRequestJSON>();
export const assertKeetaNotificationAnchorDeleteSubscriptionRequestJSON: ReturnType<typeof createAssertEquals<KeetaNotificationAnchorDeleteSubscriptionRequestJSON>> = createAssertEquals<KeetaNotificationAnchorDeleteSubscriptionRequestJSON>();
export const assertKeetaNotificationAnchorListSubscriptionsRequestJSON: ReturnType<typeof createAssertEquals<KeetaNotificationAnchorListSubscriptionsRequestJSON>> = createAssertEquals<KeetaNotificationAnchorListSubscriptionsRequestJSON>();
